In [21]:
import pandas as pd
import os

In [27]:
filenames=os.listdir('CAPSTONE DATABASE/TB NEG/Rectified/')
# dataframe = pd.DataFrame()
tbneg1 = pd.read_csv("CAPSTONE DATABASE/TB NEG/Rectified/HC001.csv")
tbneg1.drop(tbneg1.columns[0:8], axis=1)
df1 = tbneg1.mean(axis = 0)
dataframe = pd.DataFrame(df1).transpose()
for i in range(len(filenames)-1):
    tbneg = pd.read_csv("CAPSTONE DATABASE/TB NEG/Rectified/"+filenames[i+1])
    tbneg.drop(tbneg.columns[0:8], axis=1, inplace=True)
    df = tbneg.mean(axis = 0)
    df_final = pd.DataFrame(df).transpose()
    dataframe.append(df_final)
    print(dataframe)

,Time,Unnamed: 1,Unnamed: 2,Unnamed: 3,Ambient Temp [C],Therm1 [volts],Battery Raw Reading,Flag,S1,S2,...,S23,S24,S25,S26,S27,S28,S29,S30,S31,S32
0,0.6,0,0,0,35.0,1.211548,4095.0,0,5.781849,2.768626,...,0.758844,2.138055,0.576709,1.965907,0.277250,0.894820,1.019403,2.768874,0.446352,0.476987
1,1.1,0,0,0,35.0,1.212158,4095.0,0,5.780850,2.768654,...,0.758828,2.138179,0.576700,1.966035,0.277259,0.894849,1.019378,2.768695,0.446369,0.476994
2,1.7,0,0,0,35.0,1.212769,4095.0,0,5.781212,2.768640,...,0.758853,2.138109,0.576699,1.965938,0.277251,0.894808,1.019406,2.768793,0.446381,0.477000
3,2.2,0,0,0,35.0,1.210938,4095.0,0,5.780809,2.768572,...,0.758847,2.138149,0.576701,1.965759,0.277257,0.894840,1.019388,2.768863,0.446383,0.476984
4,2.8,0,0,0,35.0,1.212158,4095.0,0,5.781110,2.768540,...,0.758862,2.138098,0.576699,1.965818,0.277259,0.894841,1.019405,2.768808,0.446391,0.476984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581,324.2,0,0,0,35.0,1.210327,4095.0,0,5.774670,2.765970,...,0.757068,2.135975,0.576515,1.963023,0.277101,0.893407,1.017572,2.766430,0.444491,0.476690
582,324.7,0,0,0,35.0,1.213989,4095.0,0,5.773917,2.766070,...,0.757081,2.136088,0.576544,1.963051,0.277106,0.893405,1.017566,2.766303,0.444504,0.476685
583,325.3,0,0,0,35.0,1.212158,4095.0,0,5.774225,2.766220,...,0.757061,2.135986,0.576528,1.963100,0.277102,0.893384,1.017546,2.766391,0.444514,0.476686
584,325.8,0,0,0,35.0,1.209717,4095.0,0,5.774070,2.766223,...,0.757086,2.136055,0.576520,1.962995,0.277099,0.893392,1.017555,2.766367,0.444492,0.476678
585,326.4,0,0,0,35.0,1.216431,4095.0,0,5.773775,2.766119,...,0.757075,2.135990,0.576524,1.963167,0.277094,0.893393,1.017548,2.766312,0.444508,0.476690

In [23]:
dataframe

,Time,Unnamed: 1,Unnamed: 2,Unnamed: 3,Ambient Temp [C],Therm1 [volts],Battery Raw Reading,Flag,S1,S2,...,S23,S24,S25,S26,S27,S28,S29,S30,S31,S32
0,163.480546,124.904437,0.0,0.0,34.950853,1.212013,4095.0,4.634812,5.782133,2.769264,...,0.760718,2.138571,0.576764,1.967537,0.27727,0.895345,1.020238,2.770343,0.466101,0.477085